apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: etherpad-prod-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etherpad
      app.kubernetes.io/instance: prod
